#!/bin/sh -ex

SOURCE=$(dirname $0)
MACHINE=$(gcc -dumpmachine)
mkdir -p .modules-F842EC2E-$MACHINE-malloc_src
mkdir -p .modules-03B33CAA-$MACHINE-tools_bench
mkdir -p .modules-639A0A6D-$MACHINE-tools_bench_libc
mkdir -p .modules-F1542CA0-$MACHINE-tools_bench_threads
mkdir -p .modules-F3140049-$MACHINE-tools_bench_threads_libc
gcc -c -o .modules-F842EC2E-$MACHINE-malloc_src/malloc.o -DNDEBUG -O2 -fPIC -Wall -pthread -pipe -D_FILE_OFFSET_BITS=64 -DCCBUILD_BUNDLE_VERSION=0.1.0 -I$SOURCE/src/include $SOURCE/src/malloc.c &
wait
gcc -o libkissmalloc.so.0.1.0 -shared -pthread -Wl,-soname,libkissmalloc.so.0 .modules-F842EC2E-$MACHINE-malloc_src/malloc.o -L. -Wl,--enable-new-dtags,-rpath='$ORIGIN',-rpath='$ORIGIN'/../lib,-rpath-link=$PWD
rm -f libkissmalloc.so.0.1
rm -f libkissmalloc.so.0
rm -f libkissmalloc.so
ln -sf libkissmalloc.so.0.1.0 libkissmalloc.so.0.1
ln -sf libkissmalloc.so.0.1.0 libkissmalloc.so.0
ln -sf libkissmalloc.so.0.1.0 libkissmalloc.so
gcc -c -o .modules-03B33CAA-$MACHINE-tools_bench/main.o -DNDEBUG -O2 -fPIC -Wall -pthread -pipe -D_FILE_OFFSET_BITS=64 -DCCBUILD_BUNDLE_VERSION=0.1.0 -I$SOURCE/src/include $SOURCE/tools/bench/main.c &
wait
gcc -o kissbench -pthread .modules-03B33CAA-$MACHINE-tools_bench/main.o -L. -lkissmalloc -Wl,--enable-new-dtags,-rpath='$ORIGIN',-rpath='$ORIGIN'/../lib,-rpath-link=$PWD
gcc -c -o .modules-639A0A6D-$MACHINE-tools_bench_libc/main.o -DNDEBUG -O2 -fPIC -Wall -pthread -pipe -D_FILE_OFFSET_BITS=64 -DCCBUILD_BUNDLE_VERSION=0.1.0 $SOURCE/tools/bench_libc/main.c &
wait
gcc -o kissbench_libc -pthread .modules-639A0A6D-$MACHINE-tools_bench_libc/main.o -L. -Wl,--enable-new-dtags,-rpath='$ORIGIN',-rpath='$ORIGIN'/../lib,-rpath-link=$PWD
gcc -c -o .modules-F1542CA0-$MACHINE-tools_bench_threads/main.o -DNDEBUG -O2 -fPIC -Wall -pthread -pipe -D_FILE_OFFSET_BITS=64 -DCCBUILD_BUNDLE_VERSION=0.1.0 -I$SOURCE/src/include $SOURCE/tools/bench_threads/main.c &
wait
gcc -o kissbench_threads -pthread .modules-F1542CA0-$MACHINE-tools_bench_threads/main.o -L. -lkissmalloc -Wl,--enable-new-dtags,-rpath='$ORIGIN',-rpath='$ORIGIN'/../lib,-rpath-link=$PWD
gcc -c -o .modules-F3140049-$MACHINE-tools_bench_threads_libc/main.o -DNDEBUG -O2 -fPIC -Wall -pthread -pipe -D_FILE_OFFSET_BITS=64 -DCCBUILD_BUNDLE_VERSION=0.1.0 $SOURCE/tools/bench_threads_libc/main.c &
wait
gcc -o kissbench_threads_libc -pthread .modules-F3140049-$MACHINE-tools_bench_threads_libc/main.o -L. -Wl,--enable-new-dtags,-rpath='$ORIGIN',-rpath='$ORIGIN'/../lib,-rpath-link=$PWD
